name: WorkFlow

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v2
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/first-attempt-frontend
        tags: ${{ github.sha }}, latest
   
 
  trigger-workflow:
    name: Trigger workflow
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger infrastructure repo workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update-infrastructure
          ref: master
          inputs: '{"sha-tag" : "${{ github.sha }}"}'
          repo: mattedamo/thesis-microservices-app-backend-first-attempt-infrastructure
          token: ${{ secrets.WORKFLOW_DISPATCH }}
